apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 659942169599.dkr.ecr.us-west-2.amazonaws.com/devops-na-nuvem/dev/backend:v0.1
          ports:
          - containerPort: 80
