apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 659942169599.dkr.ecr.us-west-2.amazonaws.com/devops-na-nuvem/dev/frontend:v0.1
          ports:
          - containerPort: 80
